---
# NodePort Service â€” exposes internal MSSQL on a host port
# Connect from host: sqlcmd -S localhost,31433 -U sa -P 'Int_P@ssw0rd123'
# Or any SQL client (SSMS, Azure Data Studio, DBeaver) pointing to localhost:31433
apiVersion: v1
kind: Service
metadata:
  name: mssql-public
  namespace: etl-poc
spec:
  selector:
    app: mssql
  type: NodePort
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 31433   # Accessible on localhost:31433 from your machine
