# Template for Kubernetes Secrets
# Replace base64 values with your actual credentials
# To encode: echo -n "your_value" | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: external-db-creds
  namespace: etl-poc
type: Opaque
data:
  db:       cGxhY2Vob2xkZXI=
  user:     cGxhY2Vob2xkZXI=
  password: cGxhY2Vob2xkZXI=
  port:     cGxhY2Vob2xkZXI=
  host:     cGxhY2Vob2xkZXI=

---
apiVersion: v1
kind: Secret
metadata:
  name: internal-db-creds
  namespace: etl-poc
type: Opaque
data:
  db:       cGxhY2Vob2xkZXI=
  user:     cGxhY2Vob2xkZXI=
  password: cGxhY2Vob2xkZXI=
  host:     cGxhY2Vob2xkZXI=
  port:     cGxhY2Vob2xkZXI=
